### ISSUE TITLE
fetch: if i use PWA and Offline this catched

### ISSUE THREAD

**Issue by MM25Zamanian** [AliMD/alwatr#156]
### Package(s)

fetch

### Description

If we use this package offline
We encounter an error

https://github.com/AliMD/alwatr/blob/36cc32a1661af949975bbf4a1ff68fbacfae42d4/packages/core/fetch/src/fetch.ts#L37-L40

### Device or platform

Browser: Chrome

### Alwatr registered list

```console
[]
```

**Comment by AliMD** [comment]
این حل نشده؟!

**Comment by MM25Zamanian** [comment]
> این حل نشده؟!

نه

**Comment by AliMD** [comment]
خب حلش کن 😄
