### ISSUE TITLE
i18n and language load in first

### ISSUE THREAD

**Issue by asmanp2012** [AliMD/alwatr#160]
First culture not load:
https://github.com/AliMD/alwatr/blob/866f098b52aa6f4a9333d187725f6f335d746e7f/packages/core/i18n/src/core.ts#L43

We should use language:
https://github.com/AliMD/alwatr/blob/866f098b52aa6f4a9333d187725f6f335d746e7f/packages/core/i18n/src/core.ts#L44

**Comment by asmanp2012** [comment]
#154

**Comment by asmanp2012** [comment]
#154

**Comment by asmanp2012** [comment]
👎

**Comment by AliMD** [comment]
مگه این حل نشده؟!
#165

**Comment by AliMD** [comment]
> We should use language:

چرا؟!
نباید مثلا en-US با es-GB بتونه فرق کنه؟
حالا نخواست فقط‌ یکی شو تعریف میکنه و به ما ربطی نداره ولی نباید بیس اینطور باشه؟

**Comment by AliMD** [comment]
#288 !

**Comment by asmanp2012** [comment]
> شو تعریف میکنه و به ما ربطی نداره ولی نباید بیس اینطور باشه؟

@AliMD من نمیدونم چه تغیری روی پکیج ها دادید و باهاتون همراه نبودم در چند ماه گذشته چون واقعا نمیدونم چه اتفاقی داره میافته برای این که مشکلمم حل بشه مجبور شدم همه کدا رو کپی کردم توی پروژه خودم و اونجا تغیرات و اعمال کردم ولی

پکیج رو تست کردم ظاهرا که کار میکنه اگر مشکلی باشه همینجا باز اعلام میکنم

**Comment by AliMD** [comment]
مرسی
کلا از پایه مجدد نوشتم
فرصت کردی بخوتش و تستش کن
البته داکیومنت و دمو به روز نشده هنوز

**Comment by AliMD** [comment]
@asmanp2012 

مرسی
کلا از پایه مجدد نوشتم
فرصت کردی بخونش و تستش کن
البته داکیومنت و دمو به روز نشده هنوز

**Comment by asmanp2012** [comment]
> @asmanp2012
> 
> مرسی کلا از پایه مجدد نوشتم فرصت کردی بخونش و تستش کن البته داکیومنت و دمو به روز نشده هنوز

با کپی کد ها اوکی هستش و مشکلی نداره و همه چیز درسته ولی با نصب پکیج مشکل دارم چون هنوز پابلیش نشده

**Comment by AliMD** [comment]
آره دیگه باید مثال لینک کنی
