### ISSUE TITLE
Bug(core/router) : spelling mistake 

### ISSUE THREAD

**Issue by amiresp** [AliMD/alwatr#193]
### Package(s)

router

### Description

spelling mistake in readme.md 

[link to problem](https://github.com/AliMD/alwatr/blob/53f49cf9abf560258820809f69affedba60b14fb/packages/core/router/README.md?plain=1#L25)

### Device or platform

.

### Alwatr registered list

```console
.
```

**Comment by AliMD** [comment]
خیلی ممنون
لطفا خودت یک پول بده و یک e آخرش بزار تا جزو توسعه دهندگان alwatr بشی 😄

**Comment by amiresp** [comment]
حتما
انجام شد. 😄 💙
