### ISSUE TITLE
bug(core/storage): log with pure console

### ISSUE THREAD

**Issue by MM25Zamanian** [AliMD/alwatr#206]
### Package(s)

Don't known / other

### Description

https://github.com/AliMD/alwatr/blob/c4511e24dcd52a80d24ee63b124ccc9d4cb380c3/packages/core/storage/src/provider.ts#L43

### Device or platform

.

### Alwatr registered list

```console
.
```

**Comment by AliMD** [comment]
این از عمد به اون شکل نوشته شده تا از لاگ عادی استثنا باشه
برای بنچمارک بوده
