### ISSUE TITLE
Get All in storage

### ISSUE THREAD

**Issue by njfamirm** [AliMD/alwatr#260]
### Package(s)

Don't known / other

### Description

Sometimes we need to access all storage value...

Some thing like `getAll()`

### Proposed solution

getter return `_storage`

https://github.com/AliMD/alwatr/blob/efd08abfd30e60c5e0c674c50e5c1f1dbb0e17a6/packages/core/storage/src/storage.ts#L67

**Comment by MM25Zamanian** [comment]
@AliMD
