### ISSUE TITLE
Failed to parse source map from 'node_modules\@alwatr\fetch\src\fetch.ts'

### ISSUE THREAD

**Issue by asmanp2012** [AliMD/alwatr#388]
### Package(s)

fetch

### Description

A lot of packages were warning about not founding the .ts file
file: Error: ENOENT: no such file or directory, open '\node_modules\@alwatr\fetch\src\fetch.ts

### Device or platform

browser: chrome

### Alwatr registered list

```console
[]
```

**Comment by asmanp2012** [comment]
React say set 
GENERATE_SOURCEMAP=false
in .env to fix them warning

**Comment by AliMD** [comment]
بحث اینجاست که آیا باید فایل های ts رو پکیج باشه؟
حیفه کلا source map ساخته بشه چون بالاخره تو لاگ و .. نشون میده تو فلان جای ts خطا داریم
حالا اگر مفیده میشه تو پکیج بگیم فایل‌های ts رو هم همراه کن
