### ISSUE TITLE
Logger package issue

### ISSUE THREAD

**Issue by mohammadhonarvar** [AliMD/alwatr#441]
### Package(s)

logger

### Description

`logger.ts` In line 55, when `isBroser` is equal to `false` we can use `process.env.NODE_ENV` and we don't need to read from `globalThis`

`globalThis.process.env.NODE_ENV` has an issue with building time

### Device or platform

Vite

### Alwatr registered list

```console
What is this field exactly?!!
```

**Comment by AliMD** [comment]
done and published at `0.24.1`
