### ISSUE TITLE
افزودن مستقیم آیکون به کامپوننت آیکون

### ISSUE THREAD

**Issue by MM25Zamanian** [AliMD/alwatr#842]
### Package(s)

Don't known / other

### Description

سلام سلام

یه قابلیتی که با وجود esbuild ممکن میشه اینه که مستقیماً یه فایل SVG رو ایمپورت کنیم و بعد از بیلد به یه متغیر متنی تبدیل بشه

فقط لازمه که در کامپوننت آیکون قابلیتی وجود داشته باشه که یه ورودی متنی به عنوان آیکون بهش بدیم و درصورت وجود اون تمام پیچیدگی ها از کار بیوفته

به شخصه این کارو با درست کردن یه پکیج فقط واسه SVG آیکون ها حل کردم و پیشنهادش میکنم

خوبی این روش اینه که بعد از لود صفحه آیکون ها بدون درخواست اضافه ای هستن و از همه چی سریع تر رندر میشن (حتی از متون)

### Proposed solution

یخ بستنی مهخوری ؟

**Comment by AliMD** [comment]
اینو خودمم لازم دارم
چرا پول نمیدی خب!

**Comment by MM25Zamanian** [comment]
> اینو خودمم لازم دارم چرا پول نمیدی خب!

شما ساختار خودتون رو دارین
اما با امید به اینکه میتونم یه کار درست و حسابی انجام بدم
چشم پول ریکوعست میدم

**Comment by njfamirm** [comment]
اضافه شد
