### ISSUE TITLE
CI/CD workflow for release in github and publish to NPM

### ISSUE THREAD

**Issue by AliMD** [AliMD/alwatr#86]
### Package(s)

Don't known / other

### Description

Add some workflow for relase all packages and update changelogs

### Proposed solution

Like lit: https://github.com/lit/lit/blob/main/.github/workflows/release.yaml

**Comment by MM25Zamanian** [comment]
Can i help you ?

**Comment by omidgharib** [comment]
Interesting

**Comment by njfamirm** [comment]
Close? @AliMD
