### ISSUE TITLE
نمایش چند اسنیک بار همزمان

### ISSUE THREAD

**Issue by MM25Zamanian** [AliMD/alwatr#866]
### Package(s)

Don't known / other

### Description

سلام

آقا یه سوال این قابلیتی که نمیشه در صفحه همزمان چند اسنیک بار نمایش داد باگ محسوب میشه یا سیاست ؟؟

بنظرم چی لازمیه !

### Proposed solution

آخرش نفمیدم این چی میگه ؟

**Comment by AliMD** [comment]
لطفا سوالات خودتون رو در stack over flow و انجمن جای پسس و پاسخ مطرح اینجا
ایشو سوال نیست 😆 

ببین کلا توست پیام های بی اهمیت هستش که قبلی رو حذف میکنه مگت اینکه کلیدی داشته باشه با تایم بی نهایت که میمونه که البته میخاهم همینم بردارم
